{
 "title": "Xiaomi MI LYWSD03MMC",
 "description": "Metrics from LYWSD03MMC sensors",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature, humidity and battery",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "sensor_temperature_celsius", "legendFormat": "{{device_id}} " }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sensor_humidity_percent", "legendFormat": "{{device_id}}" }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sensor_battery_percent", "legendFormat": "{{device_id}}" }
   ]
  }
 ]
}